docs/components/filter-options.md
package.json
src/FilterOptions/index.tsx
src/FilterOptions/interface.ts

✨feat(FilterOptions):

---

docs/components/scroll-pdf.md
package.json
src/ScrollPdf/index.tsx

✨feat(scrollPdf 组件):

---

docs/components/scroll-pdf.md
package.json
src/ScrollPdf/index.tsx

✨feat(ScrollPdf组件):

---

docs/components/scroll-pdf.md
package.json
src/ScrollPdf/index.tsx

🐞fix(scrollpdf):

---

package.json

moment不加入依赖，将会自动引入，会报./locale的warning

✨feat(moment 包加入依赖):

---

package.json
src/PageTable/index.tsx

🐞fix(PageTable): 组织树取消选中时bug

---

package.json
src/ScrollPdf/index.tsx

🐞fix: ScrollPdf组件

---

docs/components/page-table.md
package.json
src/PageTable/index.tsx
src/PageTable/interface.ts

pageTable 增加 treeExtra 属性，即antd tree props

✨feat: PageTable增加属性

---

docs/components/page-table.md
package.json
src/PageTable/index.tsx
src/PageTable/interface.ts

pageTable增加treeNoCancel参数，组织树取消选中是否触发请求，true 不会触发请求

✨feat: pageTable增加参数

---

docs/components/scroll-pdf.md
package.json
src/ScrollPdf/index.tsx

✨feat: scrollpdf组件

---

docs/components/scroll-pdf.md
package.json
src/ScrollPdf/index.tsx

✨feat: scrollpdf

---

docs/components/iform.md
package.json
src/IForm/V4/index.tsx
src/IForm/V4/interface.ts

✨feat: IForm组件

---

docs/components/iform.md
package.json
src/IForm/V4/index.tsx

textarea 类型时，将传入参数 以rest形式传入组件中

✨feat: IForm

---

docs/components/scroll-pdf.md
package.json
src/scroll-pdf/index.tsx

fix: pdf缩放sacle增加

---

docs/components/rich-text.md
package.json
src/rich-text/index.tsx

Update rich text

---

package.json
src/page-table/index.tsx

Fix page table download

---

package.json
src/page-table/index.tsx
src/page-table/interface.ts

fix:修复pagetable批量删除后,选中条数不归零

---

package.json
src/page-table/index.tsx

Fix feature

---

package.json
src/i-form/index.tsx
src/i-form/interface.ts

feat: 0.3.10

---

package.json
src/i-form/index.tsx

feat: 增加密码输入框

---

package.json
src/i-form/index.tsx

fix: antd4.17.2进行了不兼容更新，回退到4.16.x

---

package.json
src/filter-options/index.tsx
src/filter-options/interface.ts
src/page-table/index.tsx
src/page-table/interface.ts

feat: 0.3.13版本更新
